### ISSUE TITLE
Dependency Conflict 

### ISSUE THREAD

**Issue by saif97** [blaugold/unsplash_client#1]
Note: I haven't posted that many issues in GitHub. Let me know if I'm missing sth. 

I'm getting the below error when running the `flutter packages get`

[habitize3] flutter packages get
Running "flutter pub get" in habitize3...                       
Because every version of flutter_test from sdk depends on collection 1.14.11 and every version of unsplash_client depends on collection ^1.14.12, flutter_test from sdk is incompatible with unsplash_client.

So, because habitize3 depends on both unsplash_client ^0.1.1 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because habitize3 depends on both unsplash_client ^0.1.1 and flutter_test any from sdk, version solving failed.)
exit code 1

Even when deleting flutter_test I'm getting conflict w/ collection 

[habitize3] flutter packages get
Running "flutter pub get" in habitize3...                       
Because every version of flutter from sdk depends on collection 1.14.11 and every version of unsplash_client depends on collection ^1.14.12, flutter from sdk is incompatible with unsplash_client.

So, because habitize3 depends on both unsplash_client ^0.1.1 and flutter any from sdk, version solving failed.
pub get failed (1; So, because habitize3 depends on both unsplash_client ^0.1.1 and flutter any from sdk, version solving failed.)
exit code 1

![image](https://user-images.githubusercontent.com/13847797/79078410-d97cb980-7d10-11ea-8a52-de93486020cb.png)

**Comment by blaugold** [comment]
Hey @saif97, I have downgraded the dependency on `collection` to `^1.14.11` in the latest release. That should solve the version conflict.
