### ISSUE TITLE
Can't load collection, always returns 404

### ISSUE THREAD

**Issue by esDotDev** [blaugold/unsplash_client#15]
I'm trying to load a collection with id: `SUK0tuMnLLw` but it always returns a 404, any ideas?
https://unsplash.com/collections/SUK0tuMnLLw/

**Comment by blaugold** [comment]
That is weird. If I try to fetch the collection like this I get a successful response:
```dart
final coll = await client.collections.get('SUK0tuMnLLw').goAndGet();
```
Do you know whether fetching other collections works?

**Comment by esDotDev** [comment]
Strange, it works for me now. I set it to public last night, maybe it takes some time to reflect the permissions? 

Sorry for the false alarm.

**Comment by blaugold** [comment]
That would make sense. I'd imagine Unsplash makes heavy use of caches.
Glad it works now :)
